name: "Release"

on:
  release:
    types: [published]

env:
  PACKAGE_NAME: wxt-extension
  CHROME_ID: CHANGE_ME
  MOZILLA_ID: wxt-extension@cssnr.com
  UPDATE_JSON: update.json

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      version: ${{ github.event.release.tag_name }} # github.ref_name can be empty
    permissions:
      contents: write

  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build]

    permissions:
      contents: write

    steps:
      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        continue-on-error: true
        run: env

      - name: "Update Release Notes Action"
        continue-on-error: true
        uses: smashedr/update-release-notes-action@master
        with:
          type: generic

      - name: "Package Changelog Action"
        continue-on-error: true
        uses: cssnr/package-changelog-action@v2

#  publish-chrome:
#    # https://developer.chrome.com/docs/webstore/using-api
#    name: "Publish Chrome"
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#    needs: [build]
#
#    environment:
#      name: chrome
#      url: "https://chromewebstore.google.com/detail/${{ env.CHROME_ID }}"
#
#    steps:
#      - name: "Download Artifacts"
#        uses: actions/download-artifact@v8
#        with:
#          name: artifacts
#
#      - name: "Validate"
#        run: |
#          ls -lAh .
#          stat "${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-chrome.zip"
#          yq -e '.version | test("${{ github.event.release.tag_name }}")' chrome-mv3/manifest.json
#          echo "::group::ls chrome-mv3"
#          ls -lAh chrome-mv3
#          echo "::endgroup::"
#          echo "::group::cat chrome-mv3/manifest.json"
#          cat chrome-mv3/manifest.json
#          echo -e "\n::endgroup::"
#
#      - name: "Install PBE"
#        run: |
#          npm i -g publish-browser-extension
#          npx publish-extension --version
#
#      # NOTE: This does not support Firefox amo-metadata
#      - name: "Publish Extension"
#        run: |
#          npx publish-extension \
#            --chrome-zip "${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-chrome.zip" \
#            --chrome-extension-id ${{ env.CHROME_ID }} \
#            --chrome-client-id ${{ secrets.WEBSTORE_CLIENT_ID }} \
#            --chrome-client-secret ${{ secrets.WEBSTORE_CLIENT_SECRET }} \
#            --chrome-refresh-token  ${{ secrets.WEBSTORE_REFRESH_TOKEN }} \
#            --chrome-publish-target default \
#            --chrome-deploy-percentage 100 \
#            --chrome-skip-submit-review
#
#      # TODO: This only submits for review! Need automation to upload signed release...
#
#  publish-mozilla:
#    # https://mozilla.github.io/addons-server/topics/api/index.html
#    name: "Publish Mozilla"
#    runs-on: ubuntu-latest
#    timeout-minutes: 60
#    needs: [build, publish-chrome]
#
#    permissions:
#      contents: write
#
#    environment:
#      name: mozilla
#      url: "${{ github.server_url }}/${{ github.repository }}/releases/latest/download/${{ env.PACKAGE_NAME }}-firefox.xpi"
#
#    steps:
#      - name: "Download Artifacts"
#        uses: actions/download-artifact@v8
#        with:
#          name: artifacts
#
#      - name: "Generate Release Notes"
#        id: notes
#        run: |
#          notes="Full Release Notes: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
#          echo "notes=$notes" >> "$GITHUB_OUTPUT"
#
#      - name: "Write AMO Metadata"
#        uses: jsdaniell/create-json@b8e77fa01397ca39cc4a6198cc29a3be5481afef # v1.2.3
#        with:
#          name: "amo-metadata.json"
#          json: '{"version": {"release_notes": {"en-US": "${{ steps.notes.outputs.notes }}"}}}'
#
#      - name: "Validate"
#        run: |
#          ls -lAh .
#          stat "${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-sources.zip"
#          yq -e '.version | test("${{ github.event.release.tag_name }}")' firefox-mv3/manifest.json
#          echo "::group::ls firefox-mv3"
#          ls -lAh firefox-mv3
#          echo "::endgroup::"
#          echo "::group::cat firefox-mv3/manifest.json"
#          cat firefox-mv3/manifest.json
#          echo -e "\n::endgroup::"
#          echo "::group::cat amo-metadata.json"
#          cat amo-metadata.json
#          echo -e "\n::endgroup::"
#
#      - name: "Sign Mozilla Addon"
#        # --channel=listed --approval-timeout=0
#        run: |
#          npx web-ext sign \
#            --api-key="${{ secrets.FIREFOX_API_KEY }}" \
#            --api-secret="${{ secrets.FIREFOX_API_SECRET }}" \
#            --channel=unlisted \
#            --source-dir="firefox-mv3" \
#            --amo-metadata="amo-metadata.json" \
#            --upload-source-code="${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-sources.zip"
#
#      - name: "Debug Artifacts"
#        continue-on-error: true
#        run: |
#          ls -lAh web-ext-artifacts
#          echo "::group::ls ."
#          ls -lAh .
#          echo "::endgroup::"
#
#      - name: "Upload to Actions"
#        uses: actions/upload-artifact@v7
#        with:
#          name: web-ext-artifacts
#          path: web-ext-artifacts
#
#      - name: "Upload to Release"
#        uses: cssnr/upload-release-action@v1
#        with:
#          overwrite: true
#          #files: "${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-sources.zip"
#          globs: web-ext-artifacts/*.xpi
#          names: "${{ env.PACKAGE_NAME }}-firefox.xpi"
#
#  update-mozilla:
#    name: "Update Mozilla"
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#    needs: [publish-mozilla]
#
#    permissions:
#      contents: write
#
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v6
#        with:
#          persist-credentials: false
#
#      - name: "Mozilla Addon Update"
#        uses: cssnr/mozilla-addon-update-action@v1
#        with:
#          url: "https://github.com/${{ github.repository }}/releases/download/{version}/${{ env.PACKAGE_NAME }}-firefox.xpi"
#          addon_id: ${{ env.MOZILLA_ID }}
#          version: ${{ github.ref_name }}
#
#      - name: "Debug ${{ env.UPDATE_JSON }}"
#        continue-on-error: true
#        run: |
#          git status
#          echo "::group::cat ${{ env.UPDATE_JSON }}"
#          cat "${{ env.UPDATE_JSON }}"
#          echo -e "\n::endgroup::"
#
#      - name: "Commit Action"
#        id: commit
#        uses: suzuki-shunsuke/commit-action@f12e2d628a4ab72dcefe7890ae07e8dbf1e201b9 # v0.1.1
#        with:
#          branch: master
#          #repository: ${{ github.repository }}
#          #files: ${{ env.UPDATE_JSON }}
#          commit_message: "Bump ${{ env.UPDATE_JSON }} to ${{ github.ref_name }}"
#          #github_token: ${{ steps.app.outputs.token }}
#          app_id: 146360
#          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
#          fail_on_self_push: false
#
#  check:
#    name: "Check"
#    if: ${{ always() }}
#    runs-on: Ubuntu-latest
#    timeout-minutes: 5
#    needs: [build, release, publish-chrome, publish-mozilla, update-mozilla]
#
#    permissions:
#      contents: write
#
#    steps:
#      - name: "Alls Green"
#        uses: re-actors/alls-green@release/v1
#        with:
#          jobs: ${{ toJSON(needs) }}
#          allowed-skips: update-mozilla
#          #allowed-failures: release
#
#      #- name: "Cleanup Release"
#      #  if: ${{ failure() }}
#      #  env:
#      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      #  run: |
#      #    echo -e "\n## Cleanup Release\n\n" >> "$GITHUB_STEP_SUMMARY"
#      #    echo -e "Deleting Release and Tag: \`${{ github.ref_name }}\`\n\n" >> "$GITHUB_STEP_SUMMARY"
#      #    if gh release delete "${{ github.ref_name }}" --repo "${{ github.repository }}" --cleanup-tag;then
#      #      echo -e "✅ Cleanup Success.\n" >> "$GITHUB_STEP_SUMMARY"
#      #    else
#      #      echo -e "⛔ Cleanup Failed!\n" >> "$GITHUB_STEP_SUMMARY"
#      #    fi
#
#      - name: "Send Notification"
#        if: ${{ !cancelled() }}
#        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1.16.0
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK }}
#          description: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
